<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- Fontfaces CSS-->
    <link href="{{asset('AdminStyle/css/font-face.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/font-awesome-4.7/css/font-awesome.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/font-awesome-5/css/fontawesome-all.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/mdi-font/css/material-design-iconic-font.min.css')}}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{{asset('AdminStyle/vendor/bootstrap-4.1/bootstrap.min.css')}}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{{asset('AdminStyle/vendor/animsition/animsition.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/wow/animate.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/css-hamburgers/hamburgers.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/slick/slick.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/select2/select2.min.css')}}" rel="stylesheet" media="all">
    <link href="{{asset('AdminStyle/vendor/perfect-scrollbar/perfect-scrollbar.css')}}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{asset('AdminStyle/css/theme.css')}}" rel="stylesheet" media="all">

</head>

        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
       
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">overview</h2>
                             
</div>
</div></div></div></div>   

</html>
<!-- end document-->
